INSERT INTO make (id, name) VALUES
(1, 'Acura'),
(2, 'Alfa Romeo'),
(3, 'Aston Martin'),
(4, 'Audi'),
(5, 'BMW'),
(6, 'Bentley'),
(7, 'Buick'),
(8, 'Cadillac'),
(9, 'Chevrolet'),
(10, 'Chrysler'),
(11, 'Daewoo'),
(12, 'Daihatsu'),
(13, 'Dodge'),
(14, 'Eagle'),
(15, 'FIAT'),
(16, 'Ferrari'),
(17, 'Fisker'),
(18, 'Ford'),
(19, 'Freightliner'),
(20, 'GMC'),
(21, 'Genesis'),
(22, 'Geo'),
(23, 'HUMMER'),
(24, 'Honda'),
(25, 'Hyundai'),
(26, 'INFINITI'),
(27, 'Isuzu'),
(28, 'Jaguar'),
(29, 'Jeep'),
(30, 'Kia'),
(31, 'Lamborghini'),
(32, 'Land Rover'),
(33, 'Lexus'),
(34, 'Lincoln'),
(35, 'Lotus'),
(36, 'MAZDA'),
(37, 'MINI'),
(38, 'Maserati'),
(39, 'Maybach'),
(40, 'McLaren'),
(41, 'Mercedes-Benz'),
(42, 'Mercury'),
(43, 'Mitsubishi'),
(44, 'Nissan'),
(45, 'Oldsmobile'),
(46, 'Panoz'),
(47, 'Plymouth'),
(48, 'Pontiac'),
(49, 'Porsche'),
(50, 'Ram'),
(51, 'Rolls-Royce'),
(52, 'SRT'),
(53, 'Saab'),
(54, 'Saturn'),
(55, 'Scion'),
(56, 'Subaru'),
(57, 'Suzuki'),
(58, 'Tesla'),
(59, 'Toyota'),
(60, 'Volkswagen'),
(61, 'Volvo'),
(62, 'smart');
INSERT INTO address (id, city, code, street) VALUES
(1, 'Poznan', '62-222', 'Jana street'),
(2, 'Warsaw', '60-333', 'Halna street');

INSERT INTO garage (id, name, address_id) VALUES
(1, 'Fast Furious Garage', 1),
(2, 'Prestige Car Garage', 2);

INSERT INTO catalog_offer (id, name, description, price, repair_time, garage_id) VALUES
(1, 'Oil change', 'Oil change description', 100.00, 30, 1),
(2, 'Tire change', 'Tire change description', 200.00, 50, 1),
(3, 'Wheel change', 'Wheel change description', 120.00, 30, 1),
(4, 'Timing belt change', 'Timing belt change description', 1500.00, 180, 1),
(5, 'Pre-purchase car inspection', 'Pre-purchase description', 300.00, 60, 1),
(6, 'Replace air filter', 'Replace air filter description', 60.00, 15, 1),
(7, 'Replace cabin filter', 'Replace cabin filter description', 50.00, 10, 1),
(8, 'Oil change', 'Oil change description', 110.00, 30, 2),
(9, 'Tire change', 'Tire change description', 220.00, 50, 2),
(10, 'Wheel change', 'Wheel change description', 130.00, 30, 2),
(11, 'Timing belt change', 'Timing belt change description', 1700.00, 180, 2),
(12, 'Pre-purchase car inspection', 'Pre-purchase description', 350.00, 60, 2),
(13, 'Replace air and cabin filter', 'Replace air and cabin description', 150.00, 25, 2);

-- INSERT INTO garage_schedule (id, work_day, start_hour, end_hour, garage_id) VALUES
-- (1, 'MONDAY', TIME '07:00:00', TIME '15:00:00', 1),
-- (2, 'TUESDAY', TIME '07:00:00', TIME '15:00:00', 1),
-- (3, 'WEDNESDAY', TIME '07:00:00', TIME '15:00:00', 1),
-- (4, 'THURSDAY', TIME '07:00:00', TIME '15:00:00', 1),
-- (5, 'FRIDAY', TIME '07:00:00', TIME '15:00:00', 1),
-- (6, 'SATURDAY', TIME '09:00:00', TIME '13:00:00', 1),
-- (7, 'SUNDAY', TIME '00:00:00', TIME '00:00:00', 1),
-- (8, 'MONDAY', TIME '08:00:00', TIME '16:00:00', 2),
-- (9, 'TUESDAY', TIME '08:00:00', TIME '16:00:00', 2),
-- (10, 'WEDNESDAY', TIME '08:00:00', TIME '16:00:00', 2),
-- (11, 'THURSDAY', TIME '08:00:00', TIME '16:00:00', 2),
-- (12, 'FRIDAY', TIME '08:00:00', TIME '16:00:00', 2),
-- (13, 'SATURDAY', TIME '08:00:00', TIME '12:00:00', 2),
-- (14, 'SUNDAY', TIME '00:00:00', TIME '00:00:00', 2);

INSERT INTO app_user (id, first_name, last_name, email, mobile, username, password, role, created_date) VALUES
(1, 'testName', 'testLastName', 'test@email.com', '00444444444', 'testuser', '$2a$12$wVZjTRY0adwXJQh6U3cGHu44Mu65camSrYpgMZIpawuFWQVnnB4lG', 'ROLE_USER', CURRENT_TIMESTAMP),
(2, 'testName', 'testLastName', 'test@email.com', '00555555555', 'testadmin', '$2a$12$wVZjTRY0adwXJQh6U3cGHu44Mu65camSrYpgMZIpawuFWQVnnB4lG', 'ROLE_ADMIN', CURRENT_TIMESTAMP);

INSERT INTO model (id, name, make_id, type) VALUES
(1, '3 Series', 5, 'SEDAN'),
(2, 'XC60', 61, 'SUV');

INSERT INTO vehicle (id, license_plate, model_id, manufactured_year, engine_type, user_id) VALUES
(1, 'PKN11111', 1, 2014, 'DIESEL', 1),
(2, 'PO11111', 2, 2018, 'PETROL', 1),
(3, 'PO99999', 2, 2020, 'DIESEL', 2);

CREATE SEQUENCE IF NOT EXISTS bookings_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS date_seq START WITH 0 INCREMENT BY 1 MINVALUE 0;
CREATE SEQUENCE IF NOT EXISTS date2_seq START WITH 0 INCREMENT BY 1 MINVALUE 0;

-- INSERT INTO visit (id, status, date, garage_id, user_id) VALUES
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date_seq') || ' days' AS INTERVAL), 1, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1),
-- (NEXTVAL('bookings_seq'), 3 , CURRENT_DATE + CAST(NEXTVAL('date2_seq') || ' days' AS INTERVAL), 2, 1);
--
-- UPDATE visit SET status = 4 WHERE EXTRACT(DOW FROM date) = 7;
--
-- UPDATE visit SET start_hour = '07:00:00' WHERE EXTRACT(DOW FROM date) < 6 AND garage_id = 1;
-- UPDATE visit SET start_hour = '09:00:00' WHERE EXTRACT(DOW FROM date) = 6 AND garage_id = 1;
-- UPDATE visit SET start_hour = '00:00:00' WHERE EXTRACT(DOW FROM date) = 7 AND garage_id = 1;
-- UPDATE visit SET end_hour = '15:00:00' WHERE EXTRACT(DOW FROM date) < 6 AND garage_id = 1;
-- UPDATE visit SET end_hour = '13:00:00' WHERE EXTRACT(DOW FROM date) = 6 AND garage_id = 1;
-- UPDATE visit SET end_hour = '00:00:00' WHERE EXTRACT(DOW FROM date) = 7 AND garage_id = 1;
--
-- UPDATE visit SET start_hour = '08:00:00' WHERE EXTRACT(DOW FROM date) <= 6 AND garage_id = 2;
-- UPDATE visit SET start_hour = '00:00:00' WHERE EXTRACT(DOW FROM date) = 7 AND garage_id = 2;
-- UPDATE visit SET end_hour = '16:00:00' WHERE EXTRACT(DOW FROM date) < 6 AND garage_id = 2;
-- UPDATE visit SET end_hour = '12:00:00' WHERE EXTRACT(DOW FROM date) = 6 AND garage_id = 2;
-- UPDATE visit SET end_hour = '00:00:00' WHERE EXTRACT(DOW FROM date) = 7 AND garage_id = 2;
--
-- INSERT INTO visit (id, status, date, start_hour, end_hour, total_cost, garage_id, user_id) VALUES
-- (123, 0, CURRENT_DATE + INTERVAL '5 days', '07:50:00', '09:10:00', 320.00, 1, 1),
-- (124, 0, CURRENT_DATE + INTERVAL '9 days', '09:40:00', '12:40:00', 1700.00, 2, 1),
-- (125, 2, CURRENT_DATE + INTERVAL '-10 days', '12:20:00', '15:20:00', 2100.00, 2, 1),
-- (126, 4, CURRENT_DATE, '03:00:00', '23:30:00', 5500.00, 1, 1);
--
-- UPDATE visit SET date = CURRENT_DATE + INTERVAL '7 days' WHERE EXTRACT(DOW FROM date) >= 6 AND status = 0;
-- UPDATE visit SET date = CURRENT_DATE + INTERVAL '-12 days' WHERE EXTRACT(DOW FROM date) >= 6 AND status = 2;

-- INSERT INTO CARS_REPAIRS (id, name, description, cost, repair_time, car_id, booking_id, service_status) VALUES
-- (1, 'Oil change', 'Oil change description', 120.00, 30, 1, 123, 2),
-- (2, 'Tire change', 'Tire change description', 200.00, 50, 1, 123, 2),
-- (3, 'Timing belt change', 'Timing belt change description', 1700.00, 180, 2, 124, 2),
-- (4, 'Timing belt change', 'Timing belt change description', 2100.00, 180, 1, 125, 6),
-- (5, 'Individual repair', 'Individual repair description', 5500.00, 1230, 1, 126, 5);