name: Codecov

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  codecov:
  
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
      
    - name: jacoco store coverage report in xml file
      run: ./gradlew test jacocoTestReport
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3.1.3
      with:
          files: build/reports/jacoco/test/jacocoTestReport.xml
