name: PMD Code Scan

on:
  pull_request:

jobs:
  scan-the-code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: pmd/pmd-github-action@v1
        with:
          rulesets: 'src/main/resources/ruleset.xml'
          analyzeModifiedFilesOnly: true

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: pmd-report.sarif